url: "mihailescum.github.io"
baseurl: ""
markdown: kramdown

tracking_id: #

header-text: Max Mihailescu
title: Max Mihailescu
author: Max Mihailescu
footer: yes

sass:
    style: compressed
    sass_dir: _sass

plugins:
    - jekyll-sitemap
    - jekyll-tidy
