# Page configuration
header-text: Max Mihailescu
title: Max Mihailescu

# Meta data
author: Max Mihailescu
description: "PhD student in Mathematics at University Bonn working on O(n)-models from Statistical Mechanics."
keywords: "Max Mihailescu, math, bonn, cv, resume"

# Further configuration
url: "mihailescum.github.io"
baseurl: ""
markdown: kramdown
footer: yes
favicon_location: #

sass:
    style: compressed
    sass_dir: _sass

plugins:    
    - jekyll-sitemap
    - jekyll-tidy

exclude:
    - LICENSE
    - README.md
